### PR TITLE
#21 booleanliteral

### PR DESCRIPTION
**Pull request by Luctia**

### CODE REVIEW

**Comment by dvcopae** [comment]
Missing tests

**Comment by Luctia** [comment]
> Missing tests

Fixed

**Comment by dvcopae** [comment]
> > Missing tests
> 
> Fixed
Could you also add two more tests, for when there is no sub-operator, and for all suboperators? I did a similar thing in my PRs.

**Comment by Luctia** [comment]
> > > Missing tests
> > 
> > 
> > Fixed
> 
> Could you also add two more tests, for when all suboperators are blocked/allowed ? I did a similar thing in my PRs.

Fixed

**Pull request merged**
